hpc <- read.csv("household_power_consumption.csv", sep = ";", na.strings = "?")
hpc <- hpc[hpc$Date == "1/2/2007" | hpc$Date == "2/2/2007",]
datetime <- strptime(paste(as.character(hpc$Date), as.character(hpc$Time)), format = "%d/%m/%Y %H:%M")
png(file = "plot4.png")
par(mfcol = c(2, 2))
plot(datetime, hpc$Global_active_power, type = "n", xlab = "", ylab = "Global Active Power")
lines(datetime, hpc$Global_active_power)
plot(datetime, hpc$Sub_metering_1, type = "n", ylab = "Energy sub metering", xlab = "")
lines(datetime, hpc$Sub_metering_1, col = "black")
lines(datetime, hpc$Sub_metering_2, col = "red")
lines(datetime, hpc$Sub_metering_3, col = "blue")
legend("topright", lty = c(1,1,1), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), box.lty=0)
plot(datetime, hpc$Voltage, type = "n", ylab="Voltage")
lines(datetime, hpc$Voltage)
plot(datetime, hpc$Global_reactive_power, type = "n", ylab="Global_reactive_power")
lines(datetime, hpc$Global_reactive_power)
dev.off()